language: java
sudo: required
jdk:
  - oraclejdk8

before_install:
  - chmod ugo+x mvnw

install:
  - ./mvnw compile

before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 4 # give xvfb some time to start

addons:
  firefox: "46.0"
cache:
  directories:
  - .autoconf
  - $HOME/.m2

jobs:
  include:
    - stage: deploy
      script:
        - sudo apt-get update && sudo apt-get install oracle-java8-installer
        - ./mvnw package -Dmaven.test.skip=true

after_success:
 - bash <(curl -s https://codecov.io/bash)