language: java
sudo: false
jdk: oraclejdk8
install: true

before_install:
  - chmod ugo+x mvnw

before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 4 # give xvfb some time to start

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  
jobs:
  include:
    - stage: unitTest
      script:
        - ./mvnw compile
    - stage: integrationTest
      addons:
        firefox: "46.0"
      script:
        - ./mvnw verify
    - stage: deploy
      script:
        - ./mvnw package -Dmaven.test.skip=true
      after_success:
       - bash <(curl -s https://codecov.io/bash)
