language: java
sudo: false # faster builds
jdk:
  - oraclejdk8

before_install:
  - chmod ugo+x mvnw

install:
  - mvn compile

before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 4 # give xvfb some time to start

addons:
  firefox: "46.0"
cache:
  directories:
  - .autoconf
  - $HOME/.m2

jobs:
  include:
    - stage: Test
      script: mvn test
    - stage: integrationTest
      script: mvn failsafe:integration-test
    - stage: deploy
      script: mvn package -Dmaven.test.skip=true

after_success:
 - bash <(curl -s https://codecov.io/bash)