language: java
sudo: false
jdk: oraclejdk8

install:
  - mvn compile
cache:
  directories:
    - .autoconf
    - $HOME/.m2
addons:
  sonarcloud:
    organization: "sklep"
    token:
      secure: ${SONAR_TOKEN}
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 4 # give xvfb some time to start

script:
  - mvn verify sonar:sonar -B
after_success:
  - bash <(curl -s https://codecov.io/bash)