language: java
sudo: false # faster builds
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod ugo+x mvnw

install:
  - ./mvnw compile

before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 4 # give xvfb some time to start

script:
  - jdk_switcher use oraclejdk8

addons:
  firefox: "46.0"
cache:
  directories:
  - .autoconf
  - $HOME/.m2

jobs:
  include:
    - stage: deploy
      script: ./mvnw package -Dmaven.test.skip=true

after_success:
 - bash <(curl -s https://codecov.io/bash)