language: java
sudo: false # faster builds
jdk:
  - oraclejdk8

before_install:
  - chmod ugo+x mvnw

install:
  - mvn compile

before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 4 # give xvfb some time to start

addons:
  firefox: "46.0"
cache:
  directories:
  - .autoconf
  - $HOME/.m2

script:
  - mvn clean verify

after_success:
 - bash <(curl -s https://codecov.io/bash)