language: java
sudo: false
jdk: oraclejdk8

before_install:
  - chmod ugo+x mvnw

install:
  - ./mvnw compile

cache:
  directories:
  - .autoconf
  - $HOME/.m2

jobs:
  include:
    - stage: integrationTest
      before_script:
       - "export DISPLAY=:99.0"
       - "sh -e /etc/init.d/xvfb start"
       - sleep 4 # give xvfb some time to start
      addons:
        firefox: "46.0"
      script:
        - ./mvnw install
    - stage: deploy
      script:
        - ./mvnw package -Dmaven.test.skip=true
      after_success:
       - bash <(curl -s https://codecov.io/bash)
