CREATE TABLE cart (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  date_time TIMESTAMP,
  PRIMARY KEY (id)
)
CREATE TABLE cart_products (
  cart_id      BIGINT NOT NULL,
  cart_item_id BIGINT NOT NULL,
  PRIMARY KEY (cart_id, cart_item_id)
)
CREATE TABLE cart_item (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  quantity   BIGINT,
  product_id BIGINT,
  PRIMARY KEY (id)
)
CREATE TABLE category (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  description VARCHAR(255),
  name        VARCHAR(255),
  PRIMARY KEY (id)
)
CREATE TABLE orders (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  price      DECIMAL(19, 2),
  cart_id    BIGINT,
  detail_id  BIGINT,
  user_order BIGINT,
  PRIMARY KEY (id)
)
CREATE TABLE product (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
  active      TINYINT (1) DEFAULT 1,
  description VARCHAR(255),
  image_url   VARCHAR(255),
  name        VARCHAR(255),
  price       DECIMAL(19, 2),
  category_id BIGINT,
  PRIMARY KEY (id)
)
CREATE TABLE shipping_detail (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
  city         VARCHAR(255),
  house_num    VARCHAR(255),
  phone_number VARCHAR(255),
  post_code    VARCHAR(255),
  street       VARCHAR(255),
  PRIMARY KEY (id)
)
CREATE TABLE users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
  active        BOOLEAN,
  email         VARCHAR(255),
  last_name     VARCHAR(255),
  name          VARCHAR(255),
  password_hash VARCHAR(255),
  role          INTEGER,
  PRIMARY KEY (id)
)
ALTER TABLE category
  ADD CONSTRAINT UK_46ccwnsi9409t36lurvtyljak UNIQUE (name)
ALTER TABLE product
  ADD CONSTRAINT UK_jmivyxk9rmgysrmsqw15lqr5b UNIQUE (name)
ALTER TABLE users
  ADD CONSTRAINT UK_6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email)
ALTER TABLE cart_products
  ADD CONSTRAINT FK1hfft7q2fu5ceyycs2mrv5bat FOREIGN KEY (cart_item_id) REFERENCES cart_item
ALTER TABLE cart_products
  ADD CONSTRAINT FKnlhjc091rdu9k5c8u9xwp280w FOREIGN KEY (cart_id) REFERENCES cart
ALTER TABLE cart_item
  ADD CONSTRAINT FKjcyd5wv4igqnw413rgxbfu4nv FOREIGN KEY (product_id) REFERENCES product
ALTER TABLE orders
  ADD CONSTRAINT FKtpihbdn6ws0hu56camb0bg2to FOREIGN KEY (cart_id) REFERENCES cart
ALTER TABLE orders
  ADD CONSTRAINT FKfex0g9gsqgwktloigxcfa3dv8 FOREIGN KEY (detail_id) REFERENCES shipping_detail
ALTER TABLE orders
  ADD CONSTRAINT FKloe8gk9gg2tdy5v0p4xjf43qv FOREIGN KEY (user_order) REFERENCES users
ALTER TABLE product
  ADD CONSTRAINT FK1mtsbur82frn64de7balymq9s FOREIGN KEY (category_id) REFERENCES category
