create table cart (id bigint generated by default as identity, date_time timestamp, primary key (id))
create table cart_products (cart_id bigint not null, cart_item_id bigint not null, primary key (cart_id, cart_item_id))
create table cart_item (id bigint generated by default as identity, quantity bigint, product_id bigint, primary key (id))
create table category (id bigint generated by default as identity, description varchar(255), name varchar(255), primary key (id))
create table orders (id bigint generated by default as identity, price decimal(19,2), cart_id bigint, detail_id bigint, user_order bigint, primary key (id))
create table product (id bigint generated by default as identity, active tinyint(1) default 1, description varchar(255), image_url varchar(255), name varchar(255), price decimal(19,2), category_id bigint, primary key (id))
create table shipping_detail (id bigint generated by default as identity, city varchar(255), house_num varchar(255), phone_number varchar(255), post_code varchar(255), street varchar(255), primary key (id))
create table users (id bigint generated by default as identity, active boolean, email varchar(255), last_name varchar(255), name varchar(255), password_hash varchar(255), role integer, primary key (id))
alter table category add constraint UK_46ccwnsi9409t36lurvtyljak unique (name)
alter table product add constraint UK_jmivyxk9rmgysrmsqw15lqr5b unique (name)
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table cart_products add constraint FK1hfft7q2fu5ceyycs2mrv5bat foreign key (cart_item_id) references cart_item
alter table cart_products add constraint FKnlhjc091rdu9k5c8u9xwp280w foreign key (cart_id) references cart
alter table cart_item add constraint FKjcyd5wv4igqnw413rgxbfu4nv foreign key (product_id) references product
alter table orders add constraint FKtpihbdn6ws0hu56camb0bg2to foreign key (cart_id) references cart
alter table orders add constraint FKfex0g9gsqgwktloigxcfa3dv8 foreign key (detail_id) references shipping_detail
alter table orders add constraint FKloe8gk9gg2tdy5v0p4xjf43qv foreign key (user_order) references users
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category
